### ISSUE TITLE
Upravit dokumentaci (readme)

### ISSUE THREAD

**Issue by MiroCillik** [keboola/forecastio-augmentation#1]
**inputTable** a **outputTable** v configu sa uz nepouzivaju, miesto nich sa to konfiguruje cez Input a Output mapping.

V input treba vybrat spravne stlpce tusim v spravnom poradi(?)
https://github.com/keboola/forecastio-augmentation/blob/master/src/Keboola/ForecastIoAugmentation/Augmentation.php#L126

**Comment by Halama** [comment]
done
