### ISSUE TITLE
Ability to get hourly forecast as well

### ISSUE THREAD

**Issue by Vfisa** [keboola/forecastio-augmentation#11]
It looks like the app currently only uses "daily" chunk from JSON response. I would like to get hour-by-hour conditions on one API call (instead of 24 API calls for each day).

https://darksky.net/dev/docs#time-machine-request
```
The hourly data block will contain data points starting at midnight (local time) of the day requested, and continuing until midnight (local time) of the following day.
```

I was thinking if users could specify what they need and the app would surface it (daily, hourly, full)

**Comment by Halama** [comment]
I think we can change a bit configuration.
So the input table will still have required lat, lon columns and optional date column.
Date column will accept only full date without time, if the date column will not be specified, current date will be used.

And there will be new parameter in configuration `period` which will have two options:
- `hourly` - hourly forecast for the specified day will be fetched from API
- `daily` - daily  forecast for the specified day will be stored

**Comment by Vfisa** [comment]
Hi, that might work!

I have also done some testing for hourly requests with the existing use case. I have sent 1.3M hourly weather requests in 100k chunks and the dev console marked that as 350k API requests. It looks like there is some intelligent grouping on their side to save the costs after all...

**Comment by Halama** [comment]
@Vfisa I have implemented the change, now you can specify `daily` or `hourly` granularity.
Can you please give it a try on some real world use case?
thanks

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/31344255-758ad25c-ad12-11e7-972c-3fd91233fbd2.png)

**Comment by Halama** [comment]
I have deprecated this repo and moved to https://github.com/keboola/darksky-augmentation
The extractor is now privately available at https://connection.keboola.com/admin/projects/3313/extractors/keboola.dark-sky-augmentation

I am closing this here, feel free to open new issue here https://github.com/keboola/darksky-augmentation/issues
